# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  # - osx

julia:
  - 1
  # - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

# avoid duplicate tests in PRs
branches:
  only:
    - main
    - dev

script:
  - julia -e 'ENV["PYTHON"]=""; using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.build(; verbose=true); Pkg.test(coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("PolynomialBases")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("PolynomialBases")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
